ignore duplicated bConfigurationValue
dorssel/usbipd-win pull request #61
Opened 2021-11-05 11:06 UTC by cho45

Fix #54 

I am not sure if this is an accurate change. However, I believe it is better than the current situation where it crashes.

2021-11-06 01:12 UTC, dorssel requested changes
For now, this will quickly avoid most problems, but I expect that if you actually want to attach *this* device (i.e. the one with multiple configuration), then we do need to parse it properly instead of just ignoring it.

Unfortunately, I don't have any such devices. Are you able/willing to do some testing in the future once I figured this out?

2021-11-06 01:12 UTC, dorssel commented on UsbIpServer/UsbConfigurationDescriptors.cs
> +                        }
```suggestion
                        if (!Configurations.TryAdd(config.bConfigurationValue, configuration))
                        {
                            Console.Error.WriteLine($"WARNING: bConfigurationValue {config.bConfigurationValue} is duplicated. ignored.");
                        }
```

2021-11-06 02:37 UTC, cho45 commented on UsbIpServer/UsbConfigurationDescriptors.cs
> +                        }
Oh, you have the right method. I've almost never written C# before, so I appreciate the pointers.

2021-11-06 02:43 UTC, cho45 commented
Of course, it is good to be able to parse just fine in such a case.

I can test it and see if there are any errors. It may be difficult to connect to the actual device having the problem with usbip to try.

2021-11-06 02:46 UTC, dorssel commented on UsbIpServer/UsbConfigurationDescriptors.cs
> +                        }
Thx for the fix. It's ok to commit the suggestion yourself, but next time you may just want to "accept". Saves you the trouble of copy/paste.

2021-11-06 02:47 UTC, dorssel approved these changes

2021-11-06 02:47 UTC, merged

2021-11-07 04:29 UTC, shanselman commented
I did some testing and can confirm that you can't attach to ANY device using usbipd attach if the dual config device is attached. It will hang here. The only solution is to remove the device (I turned mine off)

![image](https://user-images.githubusercontent.com/2892/140632304-da00d8bb-fe53-429a-bbc7-cc16406e8af7.png)

That said, you can manually bind, etc, etc, but for the very convenient "attach" command this still hangs in enumeration, perhaps on the linux side?

2021-11-07 09:19 UTC, dorssel commented
@shanselman 
Are you willing to conduct an experiment?

This code (enumeration) is used not only in CLI, but also in the service. My guess is that the blunt `Console.Error.WriteLine` is interfering with the remote command execute. What if you just comment out the WARNING? I.e. just silently ignore?

I'm still looking for a way to reproduce this myself, but no luck yet.

2021-11-15 21:50 UTC, shanselman commented
Lovely @dorssel, I see the latest release is 15 days ago, I'll install this one as soon as it's packaged up! Craig and I are going to do a promotional video on usbipd this week for my youtube!

2021-11-15 22:04 UTC, dorssel commented
Cool. I was planning for a release tomorrow or Wednesday. We're polishing some of the more common issues, some just documentation, some real. By now, the latest reported issues are >50% known and fixed, so it is time to release those fixes alright.

2021-11-15 23:47 UTC, shanselman commented
Lovely! We are recording at noon on Weds. Looking forward to the release!


On Mon, Nov 15, 2021 at 2:04 PM Frans van Dorsselaer <
***@***.***> wrote:

> Cool. I was planning for a release tomorrow or Wednesday. We're polishing
> some of the more common issues, some just documentation, some real. By now,
> the latest reported issues are >50% known and fixed, so it is time to
> release those fixes alright.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dorssel/usbipd-win/pull/61#issuecomment-969364695>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAAWTEBQJYIWJWYOD65YGTUMF7XTANCNFSM5HNSWUVQ>
> .
>